#!/usr/bin/env bash

# Based on: https://jade.fyi/blog/pinning-nixos-with-npins/

cd $PROJECT_ROOT

# assume that if there are no args, you want to switch to the configuration
cmd=${1:-switch}
shift

device_path="${DEVICE_PATH?"required"}"
device_path=$(realpath "$device_path")
npins_path="$device_path/npins/default.nix"

nixpkgs_pin=$(nix eval --raw -f $npins_path nixpkgs)
configuration_path="$device_path/configuration.nix"
nix_path="nixpkgs=${nixpkgs_pin}:nixos-config=$configuration_path"

# without --fast, nixos-rebuild will compile nix and use the compiled nix to
# evaluate the config, wasting several seconds
sudo env NIX_PATH="${nix_path}" nixos-rebuild "$cmd" --fast "$@"
